import {
  ArrowLeftRight,
  Swords,
  ShieldAlert,
  TrendingDown,
  RefreshCcw,
  LayoutList,
  Search,
  Shield,
  CloudLightning,
  Split,
  Eye,
  Target,
  GraduationCap,
  Dumbbell,
  Handshake,
  BrainCircuit,
  Globe,
  MonitorPlay,
  Book,
  Joystick,
  MessageSquare,
} from 'lucide-react';
import { ThinkingFramework } from '../types';

export const TOPIC_POOL = [
  // 社会・制度
  '週休3日制を導入すべきか',
  'ベーシックインカムの是非',
  '選挙の投票を義務化すべきか',
  '定年制を廃止すべきか',
  '夫婦別姓を認めるべきか',
  '少年法を廃止し、成人と同じ刑罰を科すべきか',
  '死刑制度は廃止すべきか',
  '首相公選制を導入すべきか',
  '日本は移民受け入れを大幅に拡大すべきか',
  '富裕層への課税を大幅に強化すべきか',
  '救急車の利用を有料化すべきか',
  'マイナンバーカードの携帯を義務化すべきか',
  'NHKの受信料制度を廃止すべきか',
  '消費税を廃止すべきか',
  '裁判員制度は廃止すべきか',
  '首都機能を東京以外に移転すべきか',
  '道州制を導入すべきか',
  '結婚制度は時代遅れか',

  // 教育・学校
  '学校でのスマホ利用禁止',
  '小学校での英語教育は必要か',
  '宿題は廃止すべきか',
  '部活動は外部委託すべきか',
  '紙の教科書を完全に廃止すべきか',
  '大学の学費を完全無償化すべきか',
  '飛び級制度を日本の公教育に導入すべきか',
  '学校の校則（髪型や服装）を全廃すべきか',
  '制服を廃止し私服登校にすべきか',
  '義務教育でのプログラミング教育をもっと強化すべきか',
  '9月入学制に移行すべきか',
  '文系・理系の区分を廃止すべきか',

  // テクノロジー・未来
  'AIは人間の仕事を奪うか',
  'キャッシュレス化を強制すべきか',
  'インターネットは実名制にすべきか',
  '遺伝子編集で能力を強化した人間を生み出すべきか',
  '自動運転車が事故を起こした場合、メーカーが全責任を負うべきか',
  '宇宙開発より地球環境にお金を使うべきか',
  'SNSの利用に年齢制限（16歳以上など）を設けるべきか',
  'フェイクニュースの発信を法的に処罰すべきか',
  '生成AIによる創作物は著作権で保護されるべきか',
  'メタバース上の犯罪を現実の法律で裁くべきか',
  '人間は不老不死を目指すべきか',
  'ドローン配送を全面的に解禁すべきか',
  '暗号資産（仮想通貨）を主要通貨として認めるべきか',

  // 倫理・環境・生活
  '動物園は廃止すべきか',
  'タバコの販売を完全に禁止すべきか',
  '安楽死を合法化すべきか',
  'ペットの販売を禁止し、保護のみにすべきか',
  '美容整形を未成年に禁止すべきか',
  '男性専用車両も導入すべきか',
  'コンビニの24時間営業は禁止すべきか',
  'プラスチック製品の製造を全面禁止すべきか',
  '肉食を禁止し、代替肉のみにすべきか',
  '原子力発電は即時撤廃すべきか',
  'ギャンブルを完全に違法化すべきか',
  '職場での飲み会（接待含む）を禁止すべきか',
  'レジ袋有料化は効果があったか',
  '代理母出産を認めるべきか',
  '出生前診断を無条件で認めるべきか',

  // ビジネス・働き方
  'リモートワークは原則廃止すべきか',
  '飲食店でのチップ制度を導入すべきか',
  '最低賃金を全国一律にすべきか',
  '副業を法律で全面的に権利として認めるべきか',
  '新卒一括採用を廃止すべきか',
  '年功序列賃金を法律で禁止すべきか',
  '企業の内部留保に課税すべきか',
  '定額働かせ放題（裁量労働制）を拡大すべきか',
];

export const FALLACY_LIST = [
  { name: 'ストローマン', eng: 'Strawman', desc: '相手の主張を歪めて攻撃する' },
  { name: '論点ずらし', eng: 'Red Herring', desc: '無関係な話題で煙に巻く' },
  { name: '早急な一般化', eng: 'Hasty Generalization', desc: '少ない事例で全体を断定' },
  { name: '誤った二分法', eng: 'False Dilemma', desc: '極端な2択を迫る' },
  { name: '人身攻撃', eng: 'Ad Hominem', desc: '人格や容姿を攻撃する' },
  { name: 'お前だって論法', eng: 'Tu Quoque', desc: '相手の行動を指摘して正当化' },
  { name: '循環論法', eng: 'Circular Reasoning', desc: '結論を前提にして回る' },
  { name: 'トーン・ポリシング', eng: 'Tone Policing', desc: '言い方や感情を非難する' },
  { name: '権威への訴え', eng: 'Appeal to Authority', desc: '疑わしい権威を利用する' },
  { name: '曖昧語法', eng: 'Equivocation', desc: '言葉の意味をすり替える' },
  { name: '誘導尋問', eng: 'Loaded Question', desc: '不利な前提を含む質問' },
  { name: '感情に訴える論証', eng: 'Appeal to Emotion', desc: '同情や恐怖を煽る' },
  { name: 'アンチ・純粋性', eng: 'No True Scotsman', desc: '定義を勝手に変える' },
  { name: 'テキサスの狙撃兵', eng: 'Texas Sharpshooter', desc: '都合の良いデータだけ抽出' },
  { name: '状況対人論証', eng: 'Ad Hominem Circumstantial', desc: '立場や利益を攻撃する' },
  { name: 'ゴールポストを動かす', eng: 'Moving the Goalposts', desc: '基準を後から変える' },
];

export const DRILL_LIST = [
  {
    name: '根拠の矛盾を突く',
    icon: ArrowLeftRight,
    desc: '論理的整合性の欠如や発言の食い違いを指摘する',
  },
  { name: 'カウンターエビデンス', icon: Swords, desc: '別の証拠や事実を提示して論破する' },
  {
    name: '証拠の不備指摘',
    icon: ShieldAlert,
    desc: 'データの出典・古さ・偏りを攻撃する (Source Integrity)',
  },
  {
    name: '重要性の軽視',
    icon: TrendingDown,
    desc: '「影響は限定的である」と矮小化する (Impact Minimization)',
  },
  {
    name: '現状改良',
    icon: RefreshCcw,
    desc: '新制度を導入せずとも現行の改善で解決できると主張する (SQI)',
  },
];

export const FRAMEWORK_LIST = [
  {
    id: ThinkingFramework.MECE,
    name: 'MECE',
    icon: LayoutList,
    desc: 'モレなくダブりなく分解する。論理思考の基礎。',
  },
  {
    id: ThinkingFramework.FIVE_WHYS,
    name: '5 Whys (なぜなぜ分析)',
    icon: Search,
    desc: '「なぜ」を5回繰り返し、根本原因を特定する。',
  },
  {
    id: ThinkingFramework.SWOT,
    name: 'SWOT分析',
    icon: Shield,
    desc: '強み・弱み・機会・脅威で現状を分析する。',
  },
  {
    id: ThinkingFramework.PEST,
    name: 'PEST分析',
    icon: CloudLightning,
    desc: '政治・経済・社会・技術のマクロ環境を分析する。',
  },
  {
    id: ThinkingFramework.LOGIC_TREE,
    name: 'ロジックツリー',
    icon: Split,
    desc: '問題をツリー状に分解し、解決策を導き出す。',
  },
  {
    id: ThinkingFramework.META_COGNITION,
    name: 'メタ認知・バイアス',
    icon: Eye,
    desc: '自分の思考の偏り（バイアス）を客観視する。',
  },
];

export const LOADING_TIPS = [
  '💡 ヒント: 相手の意見を一度受け止めてから反論すると、説得力が増します（Yes-But法）。',
  '💡 ヒント: 「事実（Fact）」と「意見（Opinion）」を明確に区別して話しましょう。',
  '💡 ヒント: 相手の論理の飛躍（隠れた前提）を見つけるのが反論のコツです。',
  '💡 ヒント: 感情的になったら深呼吸。論理は冷静な頭に宿ります。',
  '💡 ヒント: 優れたディベーターは、聴衆（ジャッジ）を味方につける話し方をします。',
  '💡 ヒント: 「なぜ？」と問い続けることで、本質的な議論が可能になります。',
  '💡 ヒント: 数字やデータを用いると、主張の客観性が一気に高まります。',
  '💡 ヒント: 相手の「定義」が曖昧なときは、そこを突くチャンスです。',
];
