export enum MiniGameType {
  EVIDENCE_FILL = 'EVIDENCE_FILL',
  FALLACY_QUIZ = 'FALLACY_QUIZ',
  ISSUE_PUZZLE = 'ISSUE_PUZZLE',
  COMBO_REBUTTAL = 'COMBO_REBUTTAL',
  FERMI_ESTIMATION = 'FERMI_ESTIMATION',
  LATERAL_THINKING = 'LATERAL_THINKING',
  ACTIVE_INOCULATION = 'ACTIVE_INOCULATION',
}
